CREATE TABLE TPP_USUARIO(
	IN_IDUSUARIO SERIAL PRIMARY KEY,
	VC_NOMBRE VARCHAR(50) NOT NULL,
	VC_APELLIDO_PARTERNO VARCHAR(50) NOT NULL,
	VC_APELLIDO_MATERNO VARCHAR(50) NOT NULL,
	VC_CODIGO VARCHAR(30) NOT NULL,
	VC_USUARIO VARCHAR(30) NOT NULL,
	VC_PASSWORD VARCHAR(20) NOT NULL,
	IN_TIPO_DOCUMENTO INT NOT NULL,
	DT_NACIMIENTO DATE NOT NULL,
	VC_PAIS CHAR(30) NOT NULL,
	VC_DEPARTAMENTO VARCHAR(50) NOT NULL,
	VC_PROVINCIA VARCHAR(50) NOT NULL,
	VC_DISTRITO VARCHAR(50) NOT NULL,
	VC_DIRECCION VARCHAR(100),
	DT_REGISTRY TIMESTAMP NOT NULL,
	VC_CELULAR VARCHAR(30) NOT NULL,
	VC_CORREO VARCHAR(50) NOT NULL
);
-- 1: DNI
-- 2: Carnet de extranjeria

CREATE TABLE TPP_TIPO_USUARIO(
	IN_IDTIPO_USUARIO SERIAL PRIMARY KEY,
	CH_TIPO CHAR(20) NOT NULL
);
-- 1: Docente
-- 2: Profesor
-- 3: Alumno
-- 4: Personal Limpieza

CREATE TABLE TPP_ROLES(
	IN_IDTIPO_USUARIO INT NOT NULL,
	IN_IDUSUARIO INT NOT NULL,
	PRIMARY KEY (IN_IDTIPO_USUARIO, IN_IDUSUARIO),
	FOREIGN KEY (IN_IDTIPO_USUARIO) REFERENCES TPP_TIPO_USUARIO(IN_IDTIPO_USUARIO),
	FOREIGN KEY (IN_IDUSUARIO) REFERENCES TPP_USUARIO(IN_IDUSUARIO)
);

